export const GIFT_PRIVACY = {
  IT: {
    eyebrow: 'Informativa legale',
    title: 'Privacy Policy',
    lastUpdated: 'Ultimo aggiornamento: 7 settembre 2026',
    intro: 'Questa informativa descrive come vengono trattati i dati personali raccolti attraverso gipivisconti.com e, in particolare, tramite il modulo del libro gratuito. I contenuti possono essere consultati anche dai bambini con l’accompagnamento di un adulto, mentre i moduli sono riservati alle persone maggiorenni; il trattamento avviene nel rispetto del Regolamento (UE) 2016/679 (GDPR) e della normativa applicabile.',
    childrenNotice: {
      heading: 'Un messaggio per i bambini',
      body: 'Puoi leggere e guardare questo sito insieme a un adulto. Nei moduli non inserire il tuo nome, la tua email, la tua data di nascita o altre informazioni personali; chiedi a un adulto di compilarli per te.',
    },
    sections: [
      { heading: '1. Titolare del trattamento', body: 'Il Titolare del trattamento è Gipi Visconti. Per richieste relative ai dati personali è possibile scrivere a info@gipivisconti.com.' },
      { heading: '2. Dati raccolti e minori', body: 'Il modulo, riservato ai maggiorenni, raccoglie il nome e l’indirizzo email dell’adulto che lo compila, oltre a una data di compleanno che può riferirsi all’adulto oppure a un minore sotto la sua responsabilità. Chi compila deve confermare di avere almeno 18 anni e, se indica dati riferiti a un minore, di essere il genitore, il tutore o una persona altrimenti autorizzata. I minori non devono inviare direttamente dati attraverso il sito e Gipi Visconti non raccoglie consapevolmente dati personali inviati direttamente da loro; gli invii diretti di un minore saranno eliminati quando verranno accertati. Per proteggere il servizio dagli abusi vengono inoltre trattati temporaneamente dati tecnici, come l’indirizzo IP e l’esito del controllo di sicurezza.' },
      { heading: '3. Finalità e base giuridica', body: 'I dati vengono utilizzati per gestire la richiesta, inviare l’email nella lingua scelta e consentire il download del libro corrispondente. Se viene selezionata la casella dedicata, nome, indirizzo email e data del compleanno vengono conservati nel profilo newsletter sulla base di un consenso facoltativo, separato e revocabile. La mancata adesione non impedisce di ricevere il libro; il controllo antiabuso risponde al legittimo interesse di proteggere il sito. Il servizio automatico relativo al regalo di compleanno non è attivo e, prima della sua eventuale introduzione, verranno fornite informazioni specifiche e una scelta separata.' },
      { heading: '4. Come funziona il trattamento', body: 'La richiesta è gestita da Cloudflare: Turnstile verifica che l’invio non sia automatizzato, mentre Workers, D1, Queues e gli asset protetti permettono di elaborare la richiesta e rendere disponibile il file. L’email viene inviata dall’indirizzo info@gipivisconti.com tramite il servizio SMTP di Proton Mail.' },
      { heading: '5. Conservazione', body: 'Nome, indirizzo email, data del compleanno e scelta relativa alla newsletter vengono conservati in forma cifrata per un massimo di 30 giorni insieme alla richiesta del libro. I dati presenti nella coda di invio vengono eliminati appena termina il tentativo di consegna. Se viene prestato il consenso alla newsletter, il profilo cifrato e la prova del consenso vengono conservati fino alla revoca. Il collegamento al libro scade dopo 72 ore e consente al massimo cinque download.' },
      { heading: '6. Destinatari e trasferimenti', body: 'Cloudflare e Proton trattano i dati necessari a fornire i rispettivi servizi secondo i propri accordi e le proprie misure di protezione. I dati conferiti attraverso il modulo non vengono venduti né ceduti per finalità pubblicitarie.' },
      { heading: '7. Tecnologie necessarie e preferenze', body: 'Turnstile utilizza le informazioni tecniche necessarie a distinguere una persona da un invio automatico; il suo token è necessario, resta valido per 300 secondi e può essere usato una sola volta. Le tecnologie necessarie restano attive perché servono al funzionamento e alla sicurezza del sito. Per la presentazione grafica, il sito carica da Google Fonts i caratteri Inter, Caveat, Cormorant Garamond e Outfit; la richiesta tecnica può comunicare a Google l’indirizzo IP e informazioni sul browser, mentre non sono stati verificati cookie specifici né tempi di conservazione per questo caricamento. La registrazione gipi_cookie_consent in localStorage è necessaria per ricordare la preferenza relativa alla categoria analitica facoltativa.' },
      {
        heading: '8. Google Tag Manager e strumenti analitici',
        body: 'Google Tag Manager è usato per gestire il tag analitico facoltativo del sito. Con l’attuale impostazione di consenso di base, il contenitore GTM-M4HRN5J8 non viene caricato finché non viene accettata la categoria analitica; non sono stati verificati cookie specifici del contenitore. Prima del caricamento, i segnali di Google Consent Mode v2 vengono impostati come negati e aggiornati in modo coerente con la scelta. Google Analytics 4, identificato da G-PJ0LWY2294, deve ricevere il consenso analitico prima di funzionare. Per impostazione predefinita GA4 utilizza i cookie _ga e _ga_PJ0LWY2294, con una durata di 2 anni che può rinnovarsi; la configurazione effettiva sul sito resta da verificare dopo l’attivazione consentita.',
        links: [
          { label: 'Informativa sulla privacy di Google', href: 'https://policies.google.com/privacy?hl=it' },
        ],
      },
      { heading: '9. Consenso, conservazione della scelta e revoca', body: 'Al primo accesso la categoria analitica non è preselezionata ed è possibile accettarla o rifiutarla. La registrazione necessaria gipi_cookie_consent viene salvata in localStorage con la versione e la lingua del testo, la data e l’ora, oltre alla scelta effettuata; resta valida per un massimo di 390 giorni, il codice del sito la elimina alla scadenza e viene invalidata prima se cambia la versione dell’informativa. Può anche essere eliminata attraverso le impostazioni del browser. Il collegamento Impostazioni cookie nel piè di pagina permette di riaprire il pannello e revocare il consenso in qualsiasi momento. In caso di revoca, la pagina viene ricaricata per interrompere gli script analitici; la revoca non pregiudica la liceità del trattamento precedente.' },
      { heading: '10. Diritti', body: 'È possibile chiedere accesso, rettifica, cancellazione, limitazione o opposizione al trattamento, quando applicabile, scrivendo a info@gipivisconti.com. Il consenso alla newsletter può essere revocato in qualsiasi momento allo stesso indirizzo oppure usando il collegamento di disiscrizione presente in ogni newsletter, senza conseguenze sulla richiesta del libro. È inoltre possibile presentare reclamo all’autorità di controllo competente.' },
      { heading: '11. Sicurezza e aggiornamenti', body: 'Sono adottate misure tecniche e organizzative adeguate, tra cui cifratura temporanea, collegamenti di download a scadenza e limiti antiabuso. Questa informativa potrà essere aggiornata se cambieranno il servizio o le norme applicabili.' },
    ],
  },
  EN: {
    eyebrow: 'Legal information',
    title: 'Privacy Policy',
    lastUpdated: 'Last updated: 7 September 2026',
    intro: 'This notice explains how personal data collected through gipivisconti.com is processed, with particular reference to the free-book form. Children may also read and look through the website’s content with an adult, while the forms are for adults only; processing is carried out in accordance with Regulation (EU) 2016/679 (GDPR) and applicable data protection law.',
    childrenNotice: {
      heading: 'A message for children',
      body: 'You can read and look through this website with an adult. Do not enter your name, email address, date of birth or any other personal information in the forms; ask an adult to complete them for you.',
    },
    sections: [
      { heading: '1. Data Controller', body: 'The Data Controller is Gipi Visconti. You can write to info@gipivisconti.com with any request concerning personal data.' },
      { heading: '2. Data collected and children', body: 'The form is restricted to adults and collects the name and email address of the adult completing it, together with a birthday date that may relate to the adult or to a child for whom they are responsible. The person completing the form must confirm that they are at least 18 years old and, if they provide details about a child, that they are the child’s parent or legal guardian, or otherwise authorised to do so. Children must not submit data directly through the website and Gipi Visconti does not knowingly collect personal data submitted directly by them; direct submissions from a child will be erased when identified. Technical data, including the IP address and the outcome of the security check, is also processed temporarily to protect the service from abuse.' },
      { heading: '3. Purpose and legal basis', body: 'The data is used to manage the request, send the email in the selected language and provide the corresponding book download. If the dedicated box is selected, the name, email address and birthday date are retained in the newsletter profile on the basis of optional, separate and withdrawable consent. Declining does not prevent delivery of the book; anti-abuse checks serve the legitimate interest of protecting the website. The automated birthday gift service is not active and, before it is introduced, specific information and a separate choice will be provided.' },
      { heading: '4. How processing works', body: 'Cloudflare handles the request: Turnstile checks that the submission is not automated, while Workers, D1, Queues and protected assets process the request and provide the file. The email is sent from info@gipivisconti.com through Proton Mail’s SMTP service.' },
      { heading: '5. Retention', body: 'The name, email address, birthday date and newsletter choice are kept in encrypted form with the book request for no more than 30 days. Data held in the delivery queue is erased as soon as the delivery attempt ends. If newsletter consent is given, the encrypted profile and proof of consent are retained until consent is withdrawn. The book link expires after 72 hours and permits no more than five downloads.' },
      { heading: '6. Recipients and transfers', body: 'Cloudflare and Proton process the data required to provide their respective services under their own agreements and safeguards. Data submitted through the form is not sold or shared for advertising purposes.' },
      { heading: '7. Necessary technologies and preferences', body: 'Turnstile uses the technical information needed to distinguish a person from an automated submission; its token is necessary, remains valid for 300 seconds and can be used only once. Necessary technologies remain active because they support the operation and security of the website. For its visual presentation, the website loads Inter, Caveat, Cormorant Garamond and Outfit from Google Fonts; the technical request may communicate the IP address and browser information to Google, while no specific cookies or retention periods have been verified for this loading process. The gipi_cookie_consent record in localStorage is necessary to remember the preference for the optional analytics category.' },
      {
        heading: '8. Google Tag Manager and analytics tools',
        body: 'Google Tag Manager is used to manage the website’s optional analytics tag. Under the current basic consent setup, container GTM-M4HRN5J8 is not loaded until the analytics category is accepted; no cookies specific to the container have been verified. Before loading, Google Consent Mode v2 signals are set to denied and then updated in line with the choice made. Google Analytics 4, identified by G-PJ0LWY2294, must receive analytics consent before operating. By default, GA4 uses the _ga and _ga_PJ0LWY2294 cookies, which last for two years and may be renewed; the website’s effective configuration remains to be verified after activation with consent.',
        links: [
          { label: 'Google Privacy Policy', href: 'https://policies.google.com/privacy?hl=en-GB' },
        ],
      },
      { heading: '9. Consent, retention of the choice and withdrawal', body: 'The analytics category is not preselected on the first visit and may be accepted or rejected. The necessary gipi_cookie_consent record is stored in localStorage with the version and language of the text, the date and time, and the choice made; it remains valid for no more than 390 days, the website code removes it when it expires and it is invalidated sooner if the notice version changes. It may also be erased through the browser settings. The Cookie settings link in the footer reopens the panel so that consent can be withdrawn at any time. Following withdrawal, the page is reloaded to stop analytics scripts; withdrawal does not affect the lawfulness of earlier processing.' },
      { heading: '10. Your rights', body: 'You may request access, rectification, erasure, restriction or objection where applicable by writing to info@gipivisconti.com. Newsletter consent may be withdrawn at any time through the same address or by using the unsubscribe link in every newsletter, without affecting the book request. You may also lodge a complaint with the competent supervisory authority.' },
      { heading: '11. Security and updates', body: 'Appropriate technical and organisational measures are used, including temporary encryption, expiring download links and anti-abuse limits. This notice may be updated if the service or the applicable law changes.' },
    ],
  },
  ES: {
    eyebrow: 'Información legal',
    title: 'Política de Privacidad',
    lastUpdated: 'Última actualización: 7 de septiembre de 2026',
    intro: 'Esta política explica cómo se tratan los datos personales recogidos a través de gipivisconti.com y, en particular, mediante el formulario del libro gratuito. Los niños también pueden leer y mirar los contenidos junto a una persona adulta, mientras que los formularios están reservados a mayores de edad; el tratamiento se realiza de conformidad con el Reglamento (UE) 2016/679 (RGPD) y la normativa aplicable.',
    childrenNotice: {
      heading: 'Un mensaje para los niños',
      body: 'Puedes leer y mirar este sitio junto a una persona adulta. No introduzcas tu nombre, tu dirección de email, tu fecha de nacimiento ni ninguna otra información personal en los formularios; pide a una persona adulta que los complete por ti.',
    },
    sections: [
      { heading: '1. Responsable del tratamiento', body: 'La responsable del tratamiento es Gipi Visconti. Para cualquier solicitud relacionada con los datos personales puedes escribir a info@gipivisconti.com.' },
      { heading: '2. Datos recogidos y menores', body: 'El formulario está reservado a personas adultas y recoge el nombre y la dirección de email de quien lo completa, además de una fecha de cumpleaños que puede referirse a esa persona o a un menor bajo su responsabilidad. Quien completa el formulario debe confirmar que tiene al menos 18 años y, si indica datos de un menor, que es su progenitor o tutor legal, o que cuenta con otra autorización para hacerlo. Los menores no deben enviar datos directamente a través del sitio y Gipi Visconti no recoge conscientemente datos personales enviados directamente por ellos; los envíos directos de un menor se eliminarán cuando se identifiquen. Para proteger el servicio frente a abusos también se tratan temporalmente datos técnicos, como la dirección IP y el resultado del control de seguridad.' },
      { heading: '3. Finalidad y base jurídica', body: 'Los datos se utilizan para gestionar la solicitud, enviar el email en el idioma elegido y permitir la descarga del libro correspondiente. Si se marca la casilla correspondiente, el nombre, la dirección de email y la fecha del cumpleaños se conservan en el perfil de la newsletter sobre la base de un consentimiento opcional, separado y revocable. No aceptarlo no impide recibir el libro; el control contra abusos responde al interés legítimo de proteger el sitio web. El servicio automático relacionado con el regalo de cumpleaños no está activo y, antes de introducirlo, se facilitará información específica y una elección separada.' },
      { heading: '4. Cómo funciona el tratamiento', body: 'Cloudflare gestiona la solicitud: Turnstile comprueba que el envío no sea automático, mientras Workers, D1, Queues y los recursos protegidos permiten procesarla y ofrecer el archivo. El email se envía desde info@gipivisconti.com mediante el servicio SMTP de Proton Mail.' },
      { heading: '5. Conservación', body: 'El nombre, la dirección de email, la fecha del cumpleaños y la elección sobre la newsletter se conservan cifrados junto con la solicitud del libro durante un máximo de 30 días. Los datos presentes en la cola de envío se eliminan al finalizar el intento de entrega. Si se presta el consentimiento para la newsletter, el perfil cifrado y la prueba del consentimiento se conservan hasta su retirada. El enlace al libro caduca a las 72 horas y permite un máximo de cinco descargas.' },
      { heading: '6. Destinatarios y transferencias', body: 'Cloudflare y Proton tratan los datos necesarios para prestar sus respectivos servicios conforme a sus acuerdos y medidas de protección. Los datos enviados mediante el formulario no se venden ni se ceden con fines publicitarios.' },
      { heading: '7. Tecnologías necesarias y preferencias', body: 'Turnstile utiliza la información técnica necesaria para distinguir a una persona de un envío automático; su token es necesario, permanece válido durante 300 segundos y solo puede utilizarse una vez. Las tecnologías necesarias permanecen activas porque permiten el funcionamiento y la seguridad del sitio web. Para su presentación gráfica, el sitio carga Inter, Caveat, Cormorant Garamond y Outfit desde Google Fonts; la solicitud técnica puede comunicar a Google la dirección IP e información sobre el navegador, mientras que no se han verificado cookies específicas ni plazos de conservación para esta carga. El registro gipi_cookie_consent en localStorage es necesario para recordar la preferencia sobre la categoría analítica opcional.' },
      {
        heading: '8. Google Tag Manager y herramientas analíticas',
        body: 'Google Tag Manager se utiliza para gestionar la etiqueta analítica opcional del sitio. Con la configuración actual de consentimiento básico, el contenedor GTM-M4HRN5J8 no se carga hasta que se acepta la categoría analítica; no se han verificado cookies específicas del contenedor. Antes de cargarlo, las señales de Google Consent Mode v2 se establecen como denegadas y después se actualizan de acuerdo con la elección. Google Analytics 4, identificado por G-PJ0LWY2294, debe recibir el consentimiento analítico antes de funcionar. De forma predeterminada, GA4 utiliza las cookies _ga y _ga_PJ0LWY2294, que duran dos años y pueden renovarse; la configuración efectiva del sitio todavía debe verificarse tras la activación consentida.',
        links: [
          { label: 'Política de Privacidad de Google', href: 'https://policies.google.com/privacy?hl=es' },
        ],
      },
      { heading: '9. Consentimiento, conservación de la elección y retirada', body: 'La categoría analítica no está preseleccionada en la primera visita y puede aceptarse o rechazarse. El registro necesario gipi_cookie_consent se guarda en localStorage con la versión y el idioma del texto, la fecha y la hora, además de la elección realizada; permanece válido durante un máximo de 390 días, el código del sitio lo elimina cuando caduca y se invalida antes si cambia la versión de la política. También puede eliminarse mediante la configuración del navegador. El enlace Configuración de cookies del pie de página permite volver a abrir el panel y retirar el consentimiento en cualquier momento. Tras la retirada, la página se recarga para detener los scripts analíticos; la retirada no afecta a la licitud del tratamiento anterior.' },
      { heading: '10. Derechos', body: 'Puedes solicitar el acceso, la rectificación, la supresión, la limitación o la oposición al tratamiento, cuando corresponda, escribiendo a info@gipivisconti.com. El consentimiento para la newsletter puede retirarse en cualquier momento a través de la misma dirección o mediante el enlace de baja incluido en cada newsletter, sin afectar a la solicitud del libro. También puedes presentar una reclamación ante la autoridad de control competente.' },
      { heading: '11. Seguridad y actualizaciones', body: 'Se aplican medidas técnicas y organizativas adecuadas, entre ellas el cifrado temporal, los enlaces de descarga con caducidad y los límites contra abusos. Esta política podrá actualizarse si cambia el servicio o la normativa aplicable.' },
    ],
  },
};
