export const GIFT_ROUTES = {
  IT: { code: 'it', path: '/it/libro-gratuito' },
  EN: { code: 'en', path: '/en/free-book' },
  ES: { code: 'es', path: '/es/libro-gratis' },
};

export const GIFT_COPY = {
  IT: {
    teaserTitle: 'Ricevi un libro in regalo',
    teaserBody: 'Scegli la lingua e ricevi via email un collegamento personale per scaricarla.',
    teaserButton: 'Scopri il regalo',
    title: 'Prova un libro',
    intro: 'Se desideri far leggere subito al tuo piccolo aspirante lettore una biografia esclusiva offerta gratuitamente da Gipi, puoi inserire qui i tuoi dati:',
    name: 'Nome',
    namePlaceholder: 'Il tuo nome',
    email: 'Email',
    emailPlaceholder: 'la.tua@email.com',
    birthday: 'Compleanno',
    privacyPrefix: 'Ho letto l’',
    privacyLink: 'informativa sulla privacy',
    privacySuffix: ' relativa alla richiesta del libro.',
    newsletterConsent: 'Desidero ricevere via email la newsletter. Il consenso è facoltativo e può essere revocato in qualsiasi momento.',
    turnstileHint: 'Il controllo Cloudflare protegge il modulo dagli invii automatici.',
    submit: 'Inviami il libro',
    sending: 'Invio della richiesta…',
    successTitle: 'Controlla la tua email',
    successBody: 'Il messaggio con il pulsante per scaricare il libro è in arrivo. Se non lo trovi, controlla anche la cartella spam.',
    again: 'Invia un’altra richiesta',
    error: 'Non è stato possibile inviare la richiesta. Riprova tra poco.',
    rateLimit: 'Sono state effettuate troppe richieste. Attendi un po’ prima di riprovare.',
    turnstileError: 'Completa il controllo di sicurezza e riprova.',
    configError: 'Il modulo non è ancora disponibile in questa anteprima.',
    seoTitle: 'Libro gratuito per iniziare a leggere | Gipi Visconti',
    seoDescription: 'Richiedi gratuitamente un libro illustrato di Gipi Visconti e ricevi via email il collegamento per scaricarlo in italiano.',
  },
  EN: {
    teaserTitle: 'Receive a book as a gift',
    teaserBody: 'Choose the language and receive a personal download link by email.',
    teaserButton: 'Discover the gift',
    title: 'Try a book',
    intro: 'If you would like your little aspiring reader to start reading an exclusive biography offered for free by Gipi, you can enter your details here:',
    name: 'Name',
    namePlaceholder: 'Your name',
    email: 'Email',
    emailPlaceholder: 'your@email.com',
    birthday: 'Birthday',
    privacyPrefix: 'I have read the ',
    privacyLink: 'Privacy Policy',
    privacySuffix: ' concerning this book request.',
    newsletterConsent: 'I would like to receive the newsletter by email. Consent is optional and may be withdrawn at any time.',
    turnstileHint: 'Cloudflare protects this form from automated submissions.',
    submit: 'Send me the book',
    sending: 'Sending your request…',
    successTitle: 'Check your email',
    successBody: 'Your message with the download button is on its way. If you cannot find it, please check your spam folder.',
    again: 'Send another request',
    error: 'We could not send your request. Please try again shortly.',
    rateLimit: 'Too many requests have been made. Please wait before trying again.',
    turnstileError: 'Complete the security check and try again.',
    configError: 'The form is not available in this preview yet.',
    seoTitle: 'Free book for beginner readers | Gipi Visconti',
    seoDescription: 'Request a free illustrated book by Gipi Visconti and receive an email with the link to download it in English.',
  },
  ES: {
    teaserTitle: 'Recibe un libro de regalo',
    teaserBody: 'Elige el idioma y recibe por email un enlace personal para descargarlo.',
    teaserButton: 'Descubre el regalo',
    title: 'Prueba un libro',
    intro: 'Si deseas que tu pequeño aspirante a lector empiece a leer una biografía exclusiva ofrecida gratuitamente por Gipi, puedes introducir aquí tus datos:',
    name: 'Nombre',
    namePlaceholder: 'Tu nombre',
    email: 'Email',
    emailPlaceholder: 'tu@email.com',
    birthday: 'Cumpleaños',
    privacyPrefix: 'He leído la ',
    privacyLink: 'Política de Privacidad',
    privacySuffix: ' relativa a la solicitud del libro.',
    newsletterConsent: 'Deseo recibir la newsletter por email. El consentimiento es opcional y puede retirarse en cualquier momento.',
    turnstileHint: 'Cloudflare protege el formulario frente a envíos automáticos.',
    submit: 'Envíame el libro',
    sending: 'Enviando la solicitud…',
    successTitle: 'Revisa tu email',
    successBody: 'El mensaje con el botón para descargar el libro está en camino. Si no lo encuentras, revisa también la carpeta de spam.',
    again: 'Enviar otra solicitud',
    error: 'No ha sido posible enviar la solicitud. Inténtalo de nuevo dentro de poco.',
    rateLimit: 'Se han realizado demasiadas solicitudes. Espera un poco antes de volver a intentarlo.',
    turnstileError: 'Completa el control de seguridad e inténtalo de nuevo.',
    configError: 'El formulario todavía no está disponible en esta vista previa.',
    seoTitle: 'Libro gratis para empezar a leer | Gipi Visconti',
    seoDescription: 'Solicita gratis un libro ilustrado de Gipi Visconti y recibe por email el enlace para descargarlo en español.',
  },
};

export const giftPathForLanguage = (language) =>
  GIFT_ROUTES[language]?.path || GIFT_ROUTES.IT.path;

export const giftLanguageForPath = (pathname) => {
  const normalizedPath = pathname === '/' ? pathname : pathname.replace(/\/+$/, '');
  return Object.entries(GIFT_ROUTES).find(([, route]) => route.path === normalizedPath)?.[0] || null;
};
